#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
	# install Homebrew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
		echo "Installing Homebrew"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	if [ -f "$HOME/.Brewfile" ]; then
		echo "Updating Homebrew bundle"
		brew bundle --global
	fi

	echo "Importing iTerm2 default profile"
	cp "$HOME/.config/iterm2/com.googlecode.iterm2.plist" "$HOME/.iterm2/"
	defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2/"

elif [ "$system_type" = "Linux" ]; then
	# install node and npm if it's missing
	if ! command -v npm >/dev/null 2>&1; then
		echo "Installation of npm on Linux currently isn't supported"
	fi
fi

# install base16-builder if it's not already installed
if ! command -v base16-builder >/dev/null 2>&1; then
	echo "Installing base16-builder"
	npm install -g base16-builder
fi

# setup vim if we've got it
if command -v vim >/dev/null 2>&1; then
	echo "Bootstraping Vim"
	vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

echo "Building vim theme"
base16-builder -s ~/.config/base16/base16-spacemacs.yml -t vim -b dark > "$HOME/.vim/colors/base16-spacemacs.vim"

echo "Building vim-airline theme"
base16-builder -s ~/.config/base16/base16-spacemacs.yml -t vim-airline -b dark > "$HOME/.vim/autoload/airline/themes/base16_spacemacs.vim"

echo "Building shell theme"
base16-builder -s ~/.config/base16/base16-spacemacs.yml -t shell -b dark > "$HOME/.config/base16/base16-spacemacs.dark.sh"

# shellcheck source=/dev/null
source ~/.bash_profile
