#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
	# install Homebrew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
		echo "Installing Homebrew"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	if [ -f "$HOME/.Brewfile" ]; then
		echo "Updating Homebrew bundle"
		brew bundle --global
	fi

	if command -v vim >/dev/null 2>&1; then
		echo "Bootstraping Vim"
		vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
	fi

	echo "Importing iTerm2 default profile"
	cp "$HOME/.config/iterm2/com.googlecode.iterm2.json" "$HOME/.iterm2/"
	defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2/"
fi
